---
# ansible-playbook main.yml
- name: Run carriagereturn on remote server
  hosts: host2
  sudo: True
  tasks:
      - name: Create postgres group
        group: name=postgres
      - name: Create postgres user
        user: name=postgres group=postgres shell=/usr/sbin/nologin
      - name: Create database data dir
        file: >
            name=/var/lib/postgresql/data
            state=directory
            owner=postgres
            group=postgres
            mode=755
      - name: Stop and remove database container
        docker: name=crdb image=localhost:5000/crdb state=absent
      - name: Start database container
        command: docker run --name=crdb -d --restart=always -v /var/lib/postgresql/data:/var/lib/postgresql/data localhost:5000/crdb
      - name: Stop and remove carriagereturn container
        docker: name=carriagereturn image=localhost:5000/carriagereturn state=absent
      - name: Start carriagereturn container
        command: docker run --name=carriagereturn -d --restart=always --link crdb:crdb localhost:5000/carriagereturn
